baseURL = "https://hvishwanath.net/"
languageCode = "en-us"
title = "Harish Vishwanath's Diary"
theme = "PaperMod"
summaryLength = 42
enableRobotsTXT = true
googleAnalytics = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "I.Did.It.My.Way - Harish Vishwanath's Diary."
  author = "Harish Vishwanath"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowToc = false
  disableSpecial1stPost = false
  ShowRssButtonInSectionTermList = true
  ShowFullTextinRSS = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20

  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/posts/"
    weight = 30
